CREATE TABLE Jadwal(
	KelasId VARCHAR(3) NOT NULL DEFAULT(''),
	Hari VARCHAR(10) NOT NULL DEFAULT(''),
	JamMulai VARCHAR(10) NOT NULL DEFAULT(''),
	JamSelesai VARCHAR(10) NOT NULL DEFAULT(''),
	MapelId VARCHAR(3) NOT NULL DEFAULT(''),

	CONSTRAINT PK_Jadwal PRIMARY KEY CLUSTERED(KelasId, Hari, JamMulai)
)