CREATE TABLE Kelas(
	KelasId VARCHAR(3) NOT NULL DEFAULT(''),
	KelasName VARCHAR(15) NOT NULL DEFAULT(''),
	WaliKelasId VARCHAR(3) NOT NULL DEFAULT(''),

	CONSTRAINT PK_Kelas PRIMARY KEY CLUSTERED(KelasId)
)