CREATE TABLE NilaiSiswa(
	SiswaId VARCHAR(5) NOT NULL DEFAULT(''),
	KelasId VARCHAR(3) NOT NULL DEFAULT(''),
	MapelId VARCHAR(3) NOT NULL DEFAULT(''),
	Nilai DECIMAL(18,2) NOT NULL DEFAULT(0),

	CONSTRAINT PK_NilaiSiswa PRIMARY KEY CLUSTERED(SiswaId, KelasId, MapelId)
)